// -------------------------------------------------------------
// 
// File Name: hdlsrc\untitled\FA.v
// Created: 2015-12-18 14:55:49
// 
// Generated by MATLAB 8.5 and HDL Coder 3.6
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FA
// Source Path: untitled/FA
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FA
          (
           A,
           B,
           C,
           S,
           Ca
          );


  input   [63:0] A;  // double
  input   [63:0] B;  // double
  input   [63:0] C;  // double
  output  S;
  output  Ca;


  real A_double;  // double
  wire A_is_not0;
  real B_double;  // double
  wire B_is_not0;
  real C_double;  // double
  wire C_is_not0;
  wire A_is_not0_1;
  wire B_is_not0_1;
  wire C_is_not0_1;
  wire B_is_not0_2;
  wire a1_out1;
  wire C_is_not0_2;
  wire a2_out1;
  wire A_is_not0_2;
  wire a3_out1;


  always @* A_double = $bitstoreal(A);

  assign A_is_not0 = A_double != 0.0;



  always @* B_double = $bitstoreal(B);

  assign B_is_not0 = B_double != 0.0;



  always @* C_double = $bitstoreal(C);

  assign C_is_not0 = C_double != 0.0;



  assign S = C_is_not0 ^ (A_is_not0 ^ B_is_not0);



  assign A_is_not0_1 = A_double != 0.0;



  assign B_is_not0_1 = B_double != 0.0;



  assign C_is_not0_1 = C_double != 0.0;



  assign B_is_not0_2 = B_double != 0.0;



  assign a1_out1 = A_is_not0_1 & B_is_not0_2;



  assign C_is_not0_2 = C_double != 0.0;



  assign a2_out1 = B_is_not0_1 & C_is_not0_2;



  assign A_is_not0_2 = A_double != 0.0;



  assign a3_out1 = C_is_not0_1 & A_is_not0_2;



  assign Ca = a3_out1 | (a1_out1 | a2_out1);



endmodule  // FA

