-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\dadda_mult\FA4.vhd
-- Created: 2015-12-15 12:20:02
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FA4
-- Source Path: dadda_mult/Subsystem/FA4
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FA4 IS
  PORT( A                                 :   IN    std_logic;
        B                                 :   IN    std_logic;
        C                                 :   IN    std_logic;
        S                                 :   OUT   std_logic;
        Ca                                :   OUT   std_logic
        );
END FA4;


ARCHITECTURE rtl OF FA4 IS

  -- Signals
  SIGNAL G1_out1                          : std_logic;
  SIGNAL G2_out1                          : std_logic;
  SIGNAL G4_out1                          : std_logic;
  SIGNAL G5_out1                          : std_logic;
  SIGNAL G3_out1                          : std_logic;

BEGIN
  G1_out1 <= C XOR (A XOR B);

  G2_out1 <= A AND B;

  G4_out1 <= B AND C;

  G5_out1 <= C AND A;

  G3_out1 <= G5_out1 OR (G2_out1 OR G4_out1);

  S <= G1_out1;

  Ca <= G3_out1;

END rtl;

