-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\dadda_mult\HA1.vhd
-- Created: 2015-12-15 12:20:02
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HA1
-- Source Path: dadda_mult/Subsystem/HA1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HA1 IS
  PORT( A                                 :   IN    std_logic;
        B                                 :   IN    std_logic;
        hS                                :   OUT   std_logic;
        hC                                :   OUT   std_logic
        );
END HA1;


ARCHITECTURE rtl OF HA1 IS

BEGIN
  hS <= A XOR B;

  hC <= A AND B;

END rtl;

